#! /usr/bin/env python

import os
import re
import sys
import subprocess

class installdeps:
	def __init__ (self):
		self.debfilename = sys.argv[1]
		self.deps = os.popen('dpkg-deb -f '+self.debfilename+' "Depends"').read().strip()
		self.installdeps(self.extractdeps())

	def extractdeps(self):
		extracted_list = self.deps.replace('\n','').replace('|',',').split(',')
		new_list = []
		for extracted_each in extracted_list:
			new_list.append(re.sub('\(.*\)','',extracted_each))
		return " ".join(new_list)

	def installdeps(self, deps):
		process = subprocess.Popen('apt-get install '+deps, shell=True, close_fds=True)
		process.wait()
		sys.exit()

if __name__ == '__main__':
	installdeps()
